---

  - name: Update apt cache
    apt: 
      update_cache: yes
      
  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - python3-pip
      - python3-venv
      - git