version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.9.5
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    environment:
      - INSTANCE_KEY=${INSTANCE_KEY}
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/${RABBITMQ_DEFAULT_VHOST}
      - BACKEND_URL=${BACKEND_URL}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}

