---
- name: Deploy Flask Application
  hosts: ec2_instances
  become: yes
  environment: "{{ env }}"           
  vars: 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:

    - name: Check Port Status Stopped
      wait_for:
        port: "{{ item }}"
        state: stopped     
        timeout: 50
      ignore_errors: no
      with_items:
        - "{{ port }}"


    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - git

    - name: Clone Github Repo      
      git:
        repo: "{{ app_repo_url }}"
        dest: /home/ubuntu/app
        update: yes
      timeout: 60

    - name: Set up Virtual Env
      command: python3 -m venv /home/ubuntu/app/venv
      args: 
        chdir: /home/ubuntu/app
        creates: /home/ubuntu/app/venv

    - name: Install application dependencies
      pip:
        requirements: /home/ubuntu/app/requirements.txt
        virtualenv: /home/ubuntu/app/venv

    - name: Set up Gunicorn
      pip: 
        name: gunicorn
        virtualenv: /home/ubuntu/app/venv

    - name: Start the application
      command: "/home/ubuntu/app/venv/bin/gunicorn --workers 4 --bind 0.0.0.0:{{ port }} src:app -D"
      args: 
        chdir: /home/ubuntu/app

    - name: Check all port numbers are accessible from the current host
      wait_for:
        port: "{{ item }}"
        state: started     
        delay: 5           
        timeout: 100        
      ignore_errors: no
      with_items:
        - "{{ port }}"

