---
- name: Deploy Node.js application
  hosts: ec2-instances
  become: true
  environment: "{{env}}"
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - check_port_available
    - nodejs
    - clone_github
    - node_deploy
    - check_port_running
