---
- name: Deploy Flask Application
  hosts: ec2_instances
  become: yes
  environment: "{{ env }}"
  vars: 
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - git

    - name: Clone Github Repo
      git:
        repo: "{{ app_repo_url }}"
        dest: /home/ubuntu/app
        update: yes
    - name: Set up Virtual Env
      command: python3 -m venv /home/ubuntu/app/venv
      args: 
        chdir: /home/ubuntu/app
        creates: /home/ubuntu/app/venv

    - name: Install application dependencies
      pip:
        requirements: /home/ubuntu/app/requirements.txt
        virtualenv: /home/ubuntu/app/venv

    - name: Set up Gunicorn
      pip: 
        name: gunicorn
        virtualenv: /home/ubuntu/app/venv

    - name: Start the application
      command: /home/ubuntu/app/venv/bin/gunicorn --workers 4 --bind 0.0.0.0:5000 src:app -D
      args: 
        chdir: /home/ubuntu/app





